-- A 업체
CREATE TABLE TABLE_DATA_1
(
    no number(10),
    create_date DATE
);

-- A
INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');



-- B 업체
CREATE TABLE TABLE_DATA_2
(
    no number(10),
    create_date DATE
);

-- B
INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');



-- MERGE 확인용 테이블 
CREATE TABLE TABLE_COLC
(
    std_date DATE,
    CHECK_DATA1 VARCHAR2(6),
    CHECK_DATA2 VARCHAR2(6)
);


select * from TABLE_DATA_1;
select * from TABLE_DATA_2;
select * from TABLE_COLC
order by std_date;

-- MERGE
--1
MERGE INTO TABLE_COLC TC
USING TABLE_DATA_1 A
ON (TC.STD_DATE = A.CREATE_DATE)
WHEN MATCHED THEN
    UPDATE SET TC.CHECK_DATA1 = 'Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (A.CREATE_DATE, 'Y', 'N');


MERGE INTO TABLE_COLC TC
USING TABLE_DATA_2 B
ON (TC.STD_DATE = B.CREATE_DATE)
WHEN MATCHED THEN
    UPDATE SET TC.CHECK_DATA2 = 'Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (B.CREATE_DATE, 'N', 'Y');

DELETE FROM TABLE_COLC;
